### ISSUE TITLE
Nginx worker processes speed improvement

### ISSUE THREAD

**Issue by abarmat** [decentraland/catalyst-owner#4]
When all request are being served by the nginx container it is advised to use a configuration that allow using many CPU to handle network workload.

`worker_processes` is set by default to 1

I could be set to `auto` to use one worker per processor.

https://nginx.org/en/docs/ngx_core_module.html#worker_processes

**Comment by adrabenche** [comment]
Solved on commit 0b41454cd28a3888e8fd3a1a18fe793c31e02e87
